### ISSUE TITLE
Newer ppa for ubuntu

### ISSUE THREAD

**Issue by purpleidea** [dominikh/go-augeas#12]
Hey @raphink want to update https://launchpad.net/~raphink/+archive/ubuntu/augeas with a 1.7 build so travis can build the latest versions of this lib with 1.7 inside?

Cheers!

**Comment by purpleidea** [comment]
Apparently @roidelapluie now tells me 1.6 is sufficient for git master of this. So sorry for the noise.

**Comment by raphink** [comment]
I'll try to update next week nonetheless. Are you integrating Augeas into mgmt?

**Comment by roidelapluie** [comment]
@raphink Yes, here is the pull request:

https://github.com/purpleidea/mgmt/pull/128

**Comment by roidelapluie** [comment]
And what it looks like: https://github.com/roidelapluie/mgmt/blob/85fe1d99f09aa8fe5b90f05b43fd6f17e6a793eb/test/shell/augeas-1.yaml
