### ISSUE TITLE
Port to pure golang implementation and remove "C"

### ISSUE THREAD

**Issue by purpleidea** [dominikh/go-augeas#16]
A pure-golang implementation of this would be better, more portable, and also allow for building with: `CGO_ENABLED=0`.
This would allow for easier reproducible builds for example, as explained here: https://go.dev/blog/rebuild

Would someone like to port this to remove the "C" implementation?

I'm considering (but have not yet decided) to drop "C" stuff in mgmt. https://github.com/purpleidea/mgmt/ if I decide to do so, and this isn't ported, then I would have to either drop the `augeas` resource entirely or at least from the default builds.

Thank you!

**Comment by dominikh** [comment]
This package is specifically a set of bindings to the Augeas library. A pure Go reimplementation of Augeas would be its own, separate project, which would require orders of magnitude more code and work. It also wouldn't be Augeas anymore, but a new project with similar goals to Augeas. That is out of scope for this project and for me.

You could also look into [modernc.org/ccgo/v3](https://pkg.go.dev/modernc.org/ccgo/v3) for a mechanical translation from C to Go.

**Comment by purpleidea** [comment]
> This package is specifically a set of bindings to the Augeas library. A pure Go reimplementation of Augeas would be its own, separate project, which would require orders of magnitude more code and work. It also wouldn't be Augeas anymore, but a new project with similar goals to Augeas. That is out of scope for this project and for me.

Yeah, i totally agree on all these points, sorry for the noise. I had figured there was no better place to track the idea than here. Since this project is kind of dormant anyways do you want to leave it open in case someone sees this and gets the idea to make a new project? I previously did a search for golang+augeas and found nothing but this.

> You could also look into [modernc.org/ccgo/v3](https://pkg.go.dev/modernc.org/ccgo/v3) for a mechanical translation from C to Go.

Neat, I didn't know about this, thanks!

**Comment by dominikh** [comment]
I don't think this would be the right place to "track the idea". Better options might be the Go mailing list or possibly the Augeas mailing list.

> in case someone sees this and gets the idea to make a new project

That seems highly unlikely. This repository averages zero views per month. I reckon [your own issue](https://github.com/purpleidea/mgmt/issues/715) has more chance of being seen, and of finding interested contributors.

**Comment by purpleidea** [comment]
Fair enough, I agree with your points! Anyways I'm glad I found this project when I did, and I hope you had fun writing it. As far as I can remember I only ever needed augeas once in my puppet scripts writing career, but I thought it was neat for those edge cases!
