### ISSUE TITLE
link to static augeas library and cross-compile

### ISSUE THREAD

**Issue by vtolstov** [dominikh/go-augeas#2]
Does it possible to link with static augeas library and enable cros-compile (i'm using go 1.5.1)

**Comment by dominikh** [comment]
These are two independent questions.

- Yes, it should be possible to statically link with augeas, given you have augeas itself linked statically, have pkg-config provide the correct flags, and set the correct flags when invoking `go build` (or a variant thereof)

- Yes, cross-compiling should be possible, given you have a C cross-compiler for the given target installed and that you set the required environment variables correctly.

Neither of these two tasks are specific to go-augeas. Setting up C cross compilers is a non-trivial task, and how to obtain a statically linked augeas depends on your system. At the least, you wouldn't want to be using glibc (assuming you're on Linux), as glibc doesn't really work well with static compilation.

This isn't really the right place to discuss this, however. You will want to look into resources about cross-compiling C itself, as well as static linking and cross-compiling with Go. I do not think that any changes to this Go package are required.
