### ISSUE TITLE
[idea] provide a reflection interface 

### ISSUE THREAD

**Issue by raphink** [dominikh/go-augeas#4]
I don't know how easy it would be, but it would be pretty cool to have something along the lines of:

```go
type Fstab struct {
  File     string `augeas:"file"`
  Vfstype  string `augeas:"vfstype"`
  Opt      map[string]string `augeas:"opt" augeas-type:"array"`
  Dump     bool `augeas:"dump"`
  Passno   bool `augeas:"passno"`
} `augeas:"/files/etc/fstab" augeas-type:"seq"`
```

The lib would then provide a `Parse` method to fill the structure from Augeas info, and a `Write` method to write back to Augeas and save.

**Comment by raphink** [comment]
I started implementing that here: https://github.com/raphink/narcissus

**Comment by dominikh** [comment]
That's a feature that should exist in a third party package (such as your `narcissus`). It's not something that I'd want to maintain in this package.

I will close this issue here.
